### ISSUE TITLE
Unable to build module with nginx-1.24.0 - Debian 11

### ISSUE THREAD

**Issue by jeraldcheong** [themagister/Nginx-DOH-Module#4]
Hi, I've been trying to compile the module for nginx-1.24.0 but I'm getting errors.

Errors below. May I know how to resolve this?

make -f objs/Makefile modules
make[1]: Entering directory '/srv/RAID/root_working/ModSecurity-Debian/nginx-1.24.0'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.24.0/debian/debuild-base/nginx-1.24.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
        -o objs/addon/nginx-doh-module-0.2/ngx_http_doh_module.o \
        ../nginx-doh-module-0.2/ngx_http_doh_module.c
../nginx-doh-module-0.2/ngx_http_doh_module.c: In function ‘ngx_http_doh_read_handler’:
../nginx-doh-module-0.2/ngx_http_doh_module.c:461:20: error: passing argument 1 of ‘ngx_array_init’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  461 |     ngx_array_init(&r->headers_out.cache_control, r->pool,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    |
      |                    ngx_table_elt_t ** {aka struct ngx_table_elt_s **}
In file included from src/core/ngx_core.h:65,
                 from ../nginx-doh-module-0.2/ngx_http_doh_module.c:8:
src/core/ngx_array.h:32:29: note: expected ‘ngx_array_t *’ but argument is of type ‘ngx_table_elt_t **’ {aka ‘struct ngx_table_elt_s **’}
   32 | ngx_array_init(ngx_array_t *array, ngx_pool_t *pool, ngx_uint_t n, size_t size)
      |                ~~~~~~~~~~~~~^~~~~
../nginx-doh-module-0.2/ngx_http_doh_module.c:477:26: error: passing argument 1 of ‘ngx_array_push’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  477 |     ccp = ngx_array_push(&r->headers_out.cache_control);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          ngx_table_elt_t ** {aka struct ngx_table_elt_s **}
In file included from src/core/ngx_core.h:65,
                 from ../nginx-doh-module-0.2/ngx_http_doh_module.c:8:
src/core/ngx_array.h:27:35: note: expected ‘ngx_array_t *’ but argument is of type ‘ngx_table_elt_t **’ {aka ‘struct ngx_table_elt_s **’}
   27 | void *ngx_array_push(ngx_array_t *a);
      |                      ~~~~~~~~~~~~~^
../nginx-doh-module-0.2/ngx_http_doh_module.c: In function ‘ngx_http_doh_tcp_read_handler’:
../nginx-doh-module-0.2/ngx_http_doh_module.c:701:20: error: passing argument 1 of ‘ngx_array_init’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  701 |     ngx_array_init(&r->headers_out.cache_control, r->pool,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    |
      |                    ngx_table_elt_t ** {aka struct ngx_table_elt_s **}
In file included from src/core/ngx_core.h:65,
                 from ../nginx-doh-module-0.2/ngx_http_doh_module.c:8:
src/core/ngx_array.h:32:29: note: expected ‘ngx_array_t *’ but argument is of type ‘ngx_table_elt_t **’ {aka ‘struct ngx_table_elt_s **’}
   32 | ngx_array_init(ngx_array_t *array, ngx_pool_t *pool, ngx_uint_t n, size_t size)
      |                ~~~~~~~~~~~~~^~~~~
../nginx-doh-module-0.2/ngx_http_doh_module.c:717:26: error: passing argument 1 of ‘ngx_array_push’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  717 |     ccp = ngx_array_push(&r->headers_out.cache_control);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          ngx_table_elt_t ** {aka struct ngx_table_elt_s **}
In file included from src/core/ngx_core.h:65,
                 from ../nginx-doh-module-0.2/ngx_http_doh_module.c:8:
src/core/ngx_array.h:27:35: note: expected ‘ngx_array_t *’ but argument is of type ‘ngx_table_elt_t **’ {aka ‘struct ngx_table_elt_s **’}
   27 | void *ngx_array_push(ngx_array_t *a);
      |                      ~~~~~~~~~~~~~^
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1854: objs/addon/nginx-doh-module-0.2/ngx_http_doh_module.o] Error 1
make[1]: Leaving directory '/srv/RAID/root_working/ModSecurity-Debian/nginx-1.24.0'
make: *** [Makefile:16: modules] Error 2

**Comment by themagister** [comment]
I have fixed the build issue and done some basic testing with Nginx versions 1.22.1, 1.23.4, and 1.24.0.  Please let me know if this works for you so I can mark this issue as resolved.

**Comment by jeraldcheong** [comment]
Great! Thank you!

I'll check back once I have a chance. Will respond once I can test it.

And I see that you have bumped it up a version too! Nice!

**Comment by jeraldcheong** [comment]
It works! Closing this.
